# 应用名称
spring:
  application:
    name: seconds
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.142.33:3306/from_zeroto_expert?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  resources:
    static-locations: classpath:/templates/redirect_login.html,classpath:/static
  redis:
    host: 123.57.142.33
    port: 6379
    password: seconds123456


# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    session:
      timeout: 86400
  max-http-header-size: 1024000
  tomcat:
    max-http-form-post-size: 1024000








